export const initialState = {
  isLoaded: false,
  data: {
    id: 4296,
    url: "http://www.tvmaze.com/shows/4296/the-tom-and-jerry-show",
    name: "The Tom and Jerry Show",
    type: "Animation",
    language: "English",
    genres: [[("Comedy", "Children")]],
    status: "Running",
    runtime: 30,
    premiered: "2014-04-09",
    officialSite: "http://www.cartoonnetwork.com/video/tomjerry/episodes/",
    schedule: { time: "09:00", days: Array(1) },
    rating: { average: null },
    weight: 0,
    network: { id: 11, name: "Cartoon Network" },
    webChannel: null,
    externals: { tvrage: 41747, thetvdb: 280446, imdb: "tt3559124" },
    image: {
      original: "",
    },
    summary: "<p>The famous cat and mouse duo is back in an all-new series",
    updated: 1573583964,
    _links: { self: { href: "http://api.tvmaze.com/shows/4296" } },
  },
  display: "hide",
  Test: "show",
  showTrailer: "",
};
